school_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SchoolUserBundle:Default:index }
    
admin_users:
    pattern: /admin/users/
    defaults: { _controller: SchoolUserBundle:Admin:listUsers }
    
admin_user_edit:
    pattern: /admin/users/edit/{userId}
    defaults: { _controller: SchoolUserBundle:Admin:editUser }
    
admin_user_add:
    pattern: /admin/users/add_user/
    defaults: { _controller: SchoolUserBundle:Admin:addUser }
    
add_task:
    pattern: /task/
    defaults: { _controller: SchoolUserBundle:Task:addTask }
    
add_tags:
    pattern: /tag/
    defaults: { _controller: SchoolUserBundle:Task:addTag }
