school_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SchoolUserBundle:Login:index }

user_edit:
    pattern: /users/edit/{userId}
    defaults: { _controller: SchoolUserBundle:UserProfile:editUser }

user_profile:
    pattern: /user_profile/
    defaults: { _controller: SchoolUserBundle:UserProfile:myProfile }
    
user_change_password:
    pattern: /user/change_password/
    defaults: { _controller: SchoolUserBundle:UserProfile:changePassword }
  
admin_users:
    pattern: /admin/users/
    defaults: { _controller: SchoolUserBundle:Admin:listUsers }
    
admin_assign_teachers:
    pattern: /admin/assign_teachers/
    defaults: { _controller: SchoolUserBundle:Admin:assignTeachers }
   
admin_assign_students:
    pattern: /admin/assign_students/
    defaults: { _controller: SchoolUserBundle:Admin:assignStudents }

admin_selected_students:
    pattern: /admin/assign_students/selectedAction/
    defaults: { _controller: SchoolUserBundle:Admin:studentSelect }
    
admin_alerts:
    pattern: /admin/alerts/
    defaults: { _controller: SchoolUserBundle:Admin:alerts }
    
teacher_homepage:
    pattern: /teacher/homepage/
    defaults: { _controller: SchoolUserBundle:Teacher:index }
    
teacher_add_lecture:
    pattern: /teacher/{courseId}
    defaults: { _controller: SchoolUserBundle:Teacher:addLecture }

teacher_list_courses:
    pattern: /teacher/list_courses/
    defaults: { _controller: SchoolUserBundle:Teacher:listCourses }

teacher_list_exams:
    pattern: /teacher/list_exams/{course_id}/{class_id}
    defaults: { _controller: SchoolUserBundle:Teacher:listExams }

teacher_add_assigned_exam:
    pattern: /teacher/assigned_exam/{course_id}/{class_id}/{exam_id}
    defaults: { _controller: SchoolUserBundle:Teacher:AddAssignedExam }
    
teacher_edit_assigned_exam:
    pattern: /teacher/edit_assigned_exam/{assignedExam_id}/{course_id}/{class_id}
    defaults: { _controller: SchoolUserBundle:Teacher:editAssignedExam }
    
teacher_add_exam:
    pattern: /teacher/add_exam/{course_id}/{class_id}
    defaults: { _controller: SchoolUserBundle:Teacher:addExam }
    
teacher_edit_exam:
    pattern: /teacher/edit_exam/{exam_id}/{class_id}
    defaults: { _controller: SchoolUserBundle:Teacher:editExam }
    
teacher_remove_exam:
    pattern: /teacher/remove_exam/{exam_id}
    defaults: { _controller: SchoolUserBundle:Teacher:removeExam }
    
teacher_load_students:
    pattern: /teacher/students/
    defaults: { _controller: SchoolUserBundle:Teacher:loadStudents }
    
teacher_student_profile:
    pattern: /teacher/student/{student_id}
    defaults: { _controller: SchoolUserBundle:Teacher:studentAcademicProfile }

student_list_courses:
    pattern: /student/courses/{course_id}
    defaults: { _controller: SchoolUserBundle:Student:listCourses }
    
student_exam:
    pattern: /student/exam/{assignedExam_id}
    defaults: { _controller: SchoolUserBundle:Student:exam }