school_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SchoolUserBundle:Login:index }
    
admin_users:
    pattern: /admin/users/
    defaults: { _controller: SchoolUserBundle:Admin:listUsers }
    
admin_user_edit:
    pattern: /admin/users/edit/{userId}
    defaults: { _controller: SchoolUserBundle:Admin:editUser }
    
admin_assign_teachers:
    pattern: /admin/assign_teachers/
    defaults: { _controller: SchoolUserBundle:Admin:assignTeachers }
   
admin_assign_students:
    pattern: /admin/assign_students/
    defaults: { _controller: SchoolUserBundle:Admin:assignStudents }

admin_selected_students:
    pattern: /admin/assign_students/selectedAction/
    defaults: { _controller: SchoolUserBundle:Admin:studentSelect }
    
teacher_homepage:
    pattern: /teacher/homepage/
    defaults: { _controller: SchoolUserBundle:Teacher:index }
    
teacher_add_lecture:
    pattern: /teacher/{courseClassId}
    defaults: { _controller: SchoolUserBundle:Teacher:addLecture }