parameters:
#    school_user.example.class: School\UserBundle\Example

services:
#    school_user.example:
#        class: %school_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    school_user.file_type_extension:
        class: School\UserBundle\Form\Extension\FileTypeExtension
        tags:
            - { name: form.type_extension, alias: file }