parameters:
#    school_user.example.class: School\UserBundle\Example

services:
#    school_user.example:
#        class: %school_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    school_user.file_type_extension:
        class: School\UserBundle\Form\Extension\FileTypeExtension
        tags:
            - { name: form.type_extension, alias: file }
            
    form.type.user:
        class: School\UserBundle\Form\Type\UserType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: user_type }

    alerts:
        class: School\UserBundle\Service\Alerts
        arguments: ['@doctrine.orm.entity_manager']