school_user:
    resource: "@SchoolUserBundle/Resources/config/routing.yml"
    prefix:   /
    
homepage:
    path: /
    defaults: { _controller:SchoolUserBundle:Homepage:homepage }
    
news:
    path: /news/
    defaults: { _controller:SchoolUserBundle:Guest:news }

login: 
    path: /login
    defaults: { _controller: SchoolUserBundle:Login:login }
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
login_success:
    path: /login_success
    defaults: { _controller: SchoolUserBundle:Login:loginSuccess }
    
register:
    pattern: /register/
    defaults: { _controller: SchoolUserBundle:Login:register }
   
admin_area:
    pattern: /admin/
    defaults: { _controller: SchoolUserBundle:Admin:admin }
    
teacher_area:
    pattern: /teacher/
    defaults: { _controller: SchoolUserBundle:Login:teacher }
    
student_area:
    pattern: /student/
    defaults: { _controller: SchoolUserBundle:Login:student }
