security:
    encoders:
        School\UserBundle\Entity\User:
            algorithm: bcrypt
            
    role_hierarchy:
        
    providers:
        main:
            entity: 
                class: School\UserBundle\Entity\User
                property: username
            
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            #http_basic: ~
            form_login: 
                login_path: login 
                check_path: login_check
                default_target_path: homepage
            logout:
                path: /logout
                target: /
            
    access_control:
        # - { path: ^/admin/, roles: ROLE_ADMIN }