School\UserBundle\Entity\CourseClass:
    type: entity
    repositoryClass: School\UserBundle\Entity\CourseClassRepository
    table: course_class
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    uniqueConstraints:
        search_idx:
            columns: [course_id, class_id]
    manyToOne:
        teacher:
            targetEntity: Teacher
            inversedBy: courseClasses
            joinColumn:
                name: teacher_id
                referencedColumnName: id
        course:
            targetEntity: Course
            inversedBy: courseClasses
            joinColumn: 
                name: course_id
                referencedColumnName: id
        class:
            targetEntity: SchoolClass
            inversedBy: courseClasses
            joinColumn: 
                name: class_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
