School\UserBundle\Entity\Course:
    type: entity
    repositoryClass: School\UserBundle\Entity\CourseRepository
    table: course
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
    manyToOne: 
        schoolYear:
            targetEntity: SchoolYear
            inversedBy: courses
            joinColumn:
                name: schoolYear_id
                referencedColumnName: id
    oneToMany:
        courseClasses:
            targetEntity: CourseClass
            mappedBy: course
        exams:
            targetEntity: Exam
            cascade: [persist]
            mappedBy: course
    lifecycleCallbacks: {  }
