School\UserBundle\Entity\Lecture:
    type: entity
    table: lecture
    repositoryClass: School\UserBundle\Entity\LectureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks:
        prePersist: [preUpload]
        preUpdate: [preUpload]
        postPersist: [upload]
        postUpdate: [upload]
        postRemove: [removeUpload]
    fields:
        name:
            type: string
            length: 255
        path:
            type: string
            length: 255
            nullable: true
    manyToOne:
        courseClass:
            targetEntity: CourseClass
            inversedBy: lectures
            joinColumn:
                name: courseClass_id
                referencedColumnName: id
