School\UserBundle\Entity\Role:
    type: entity
    repositoryClass: School\UserBundle\Entity\RoleRepository
    table: roles
    id:
        id:
            type: integer
            generator: {strategy: AUTO }
    fields:
        name: 
            type: string
            length: 30
        role:
            type: string
            length: 20
            unique: true
    manyToMany:
        users:
            targetEntity: User 
            mappedBy: roles
