School\UserBundle\Entity\Student:
    type: entity
    repositoryClass: School\UserBundle\Entity\StudentRepository
    table: student
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        registrationDate:
            type: date
            nullable: true
    oneToOne:
        user:
            targetEntity: User
            inversedBy: student
            joinColumn: 
                name: user_id
                referencedColumnName: id  
    manyToOne:
        schoolClass:
            targetEntity: SchoolClass
            inversedBy: students
            joinColumn:
                name: schoolClass_id
                referencedColumnName: id
    oneToMany:
        takenExams:
            targetEntity: TakenExam
            mappedBy: student
    lifecycleCallbacks: {  }

