School\UserBundle\Entity\TakenExam:
    type: entity
    table: taken_exam
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        score:
            type: integer
            nullable: true
    manyToOne:
        student:
            targetEntity: Student
            inversedBy: takenExams
            joinColumn:
                name: student_id
                referencedColumnName: id
        exam:
            targetEntity: Exam
            inversedBy: takenExams
            joinColumn: 
                name: exam_id
                referencedColumnName: id
        assignedExam:
            targetEntity: AssignedExam
            inversedBy: takenExams
            joinColumn: 
                name: assignedExam_id
                referencedColumnName: id
    oneToMany:
        takenQuestions:
            targetEntity: TakenQuestion
            cascade: [persist]
            mappedBy: takenExam
    lifecycleCallbacks: {  }
