School\UserBundle\Entity\Teacher:
    type: entity
    repositoryClass: School\UserBundle\Entity\TeacherRepository
    table: teacher
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        user:
            targetEntity: User
            inversedBy: teacher
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToMany:
        courseClasses:
            targetEntity: CourseClass
            mappedBy: teacher
    lifecycleCallbacks: {  }
