School\UserBundle\Entity\Teacher:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        users:
            targetEntity: User 
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToMany:
        courseClasses:
            targetEntity: CourseClass
            mappedBy: teacher
    lifecycleCallbacks: {  }
