<?php

namespace School\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends EntityRepository
{
    public function findAssignedExamsByCourseClass($course, $class)
    {
        $exams = $this->getEntityManager()
            ->createQuery('SELECT e 
                FROM SchoolUserBundle:Exam e 
                LEFT JOIN e.assignedExams a 
                WHERE a.schoolClass = :class AND e.course = :course'
            )->setParameter('course', $course)
            ->setParameter('class', $class)
            ->getResult();
        return $exams;
    }
}