<?php

namespace School\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LectureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectureRepository extends EntityRepository
{
    public function loadLecturesPerCourse($course)
    {
        $lectures = $this->getEntityManager()
            ->createQuery("SELECT l 
                FROM SchoolUserBundle:Lecture l 
                WHERE l.course = :course
                ORDER BY l.uploadDate DESC"
            )->setParameter('course', $course)
        ->getResult();
        
        return $lectures;
    }
}
