<?php

namespace School\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchoolYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolYearRepository extends EntityRepository
{
}
